on:
  workflow_call:
    inputs:
      app_type: # Pass the input or secret from the caller workflow.
        required: true
        type: string
      app_name:
        required: true
        type: string

jobs:
  docker-build-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Download Dependencies
        run: |
          if [ ${{inputs.app_type}} == 'java' ]; then
            nvm package
          fi
      - name: Docker Build
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 804756348441.dkr.ecr.us-east-1.amazonaws.com
          docker build -t 804756348441.dkr.ecr.us-east-1.amazonaws.com/${{inputs.app_name}}:${GITHUB_SHA} .
          docker push 804756348441.dkr.ecr.us-east-1.amazonaws.com/${{inputs.app_name}}:${GITHUB_SHA}

## Python and Nodejs does not have anything to do at build phase
#  nodejs:
#    runs-on: self-hosted
#    if: inputs.app_type == 'nodejs'
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run a one-line script
#        run: echo Hello, world!
#
#  python:
#    runs-on: self-hosted
#    if: inputs.app_type == 'python'
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run a one-line script
#        run: echo Hello, world!
