on:
  workflow_call:
    inputs:
      app_type: # Pass the input or secret from the caller workflow.
        required: true
        type: string
jobs:
  java:
    runs-on: self-hosted
    if: ${{ inputs.app_type }} == 'java'
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
